#==============================================================================#
#---------     Options for Steps in Targeted Probe Design Pipeline     --------#
#==============================================================================#

[general]
  final_probe_amount = 20
  final_probe_random = true
  probe_length = 40
  prokka_prediction_suffix = '.ffn'
  genome_bins_suffix = '.fasta'

[gc_percent]
  min_percent = 45
  max_percent = 65

[catch]
  probe_length = 40
  probe_stride = 20
  reuse_existing_probe_files = false

[paths]
  # Where are your source data files? Where do you want the resulting files located?
  working_dir = 'pipeline_results' # working_dir: 'This is the place to work on files... (default "pipeline_results")'
  genome_bins = 'cluster_genome_bins'
  prokka_dir  = 'cluster_prokka_annotations' # files in this dir used for creating new blastdbs
  use_blastdb = '' # can be "any_preexisting_db_path" or empty if new blastdbs to be created.

[blastn]
  evalue = 0.001
  dust = 'no'
  num_alignments = 250 # Integer >1. (blastn default: 250)
  num_threads    = 2   # how many cpus?

  fields = [ 'qseqid', 'sseqid', 'pident', 'length', 'qseq' ] # plus others, e.g.: 'mismatch gapopen qstart qend sstart send evalue bitscore'
  # fields: The first 5 fields are significant, as some are used in later filtering and evaluating! Feel free to add others, but take care in any deletions!

[regexes]
  musicc_regex = [
    '_asd', '_metK', '_pgk', '_adk', '_eno', '_tpiA', '_tyrS', '_trpS',
    '_thrS', '_leuS', '_ileS', '_alaS', '_valS', '_metG', '_serS',
    '_aspS', '_proS', '_cysS', '_argS', '_pheS', '_pheT', '_hisS',
    '_pyrG', '_tsf', '_infB', '_ksgA', '_nusA', '_nusG', '_prfA',
    '_frr', '_rpoA', '_secY', '_ffh', '_ftsY', '_mraW', '_rnhB',
    '_smpB', '_grpE', '_uvrB', '_ychF', '_pyrH', '_nth', '_rsmH',
    'tRNA_ligase'
  ]
  trna_regex = [
    '50S', '5S', '16S', '30S', '23S', 'repeat', 'tRNA-Ala', 'tRNA-Arg',
    'tRNA-Asn', 'tRNA-Asp', 'tRNA-Cys', 'tRNA-Glu', 'tRNA-Gln',
    'tRNA-Gly', 'tRNA-His', 'tRNA-Ile', 'tRNA-Leu', 'tRNA-Lys',
    'tRNA-Met', 'tRNA-Phe', 'tRNA-Pro', 'tRNA-Ser', 'tRNA-Thr',
    'tRNA-Trp', 'tRNA-Tyr', 'tRNA-val', 'hypothetical'
  ]

[APPS]
  # Use only the main executable name if they are in your $PATH !
  # e.g. load the required 'module's before running this pipeline.
  catch = 'catch_design.py'
  blastdb = 'makeblastdb'
  blastn = 'blastn'

